/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class methods_JNIPowerCalculator */

#ifndef _Included_methods_JNIPowerCalculator
#define _Included_methods_JNIPowerCalculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     methods_JNIPowerCalculator
 * Method:    calculate
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_methods_JNIPowerCalculator_calculate
  (JNIEnv *, jclass, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif